config/routes.rb
SixSigmaWebServce::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  resources :quality_specifications 
  get 'quality_specifications_init' => 'quality_specifications#initialise_db'
  resources :change_loggings
  get 'change_loggings_deleteall' => 'change_loggings#deleteall'
  resources :test_codes
end

app/models/change_logging.rb
class ChangeLogging < ActiveRecord::Base
  attr_accessible :logRecord, :user_id, :user_email
  
  validates :logRecord, :presence => true
end

app/controllers/change_loggings_controller.rb
class ChangeLoggingsController < ApplicationController
  
  # ßbefore_filter :authenticate_user!
  
  # GET /change_loggings
  # GET /change_loggings.json
  def index
    @change_loggings = ChangeLogging.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @change_loggings }
    end
  end

  # GET /change_loggings/1
  # GET /change_loggings/1.json
  def show
    @change_logging = ChangeLogging.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @change_logging }
    end
  end

  # GET /change_loggings/new
  # GET /change_loggings/new.json
  def new
    @change_logging = ChangeLogging.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @change_logging }
    end
  end

  # GET /change_loggings/1/edit
  def edit
    @change_logging = ChangeLogging.find(params[:id])
  end

  # POST /change_loggings
  # POST /change_loggings.json
  def create
    @change_logging = ChangeLogging.new(params[:change_logging], :user_id => current_user.id, :user_email => current_user.email)

    respond_to do |format|
      if @change_logging.save
        format.html { redirect_to @change_logging, notice: 'Change logging was successfully created.' }
        format.json { render json: @change_logging, status: :created, location: @change_logging }
      else
        format.html { render action: "new" }
        format.json { render json: @change_logging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /change_loggings/1
  # PUT /change_loggings/1.json
  def update
    @change_logging = ChangeLogging.find(params[:id])

    respond_to do |format|
      if @change_logging.update_attributes(params[:change_logging])
         changeLogging = ChangeLogging.new(:logRecord => 'Log record updated', :users_id => current_user.id, :user_email => current_user.email)
         changeLogging.save
        format.html { redirect_to @change_logging, notice: 'Change logging was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @change_logging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /change_loggings/1
  # DELETE /change_loggings/1.json
  def destroy
    @change_logging = ChangeLogging.find(params[:id])
    @change_logging.destroy
    
    changeLogging = ChangeLogging.new(:logRecord => 'Log record deleted', :user_id => current_user.id , :user_email => current_user.email)
    changeLogging.save

    respond_to do |format|
      format.html { redirect_to change_loggings_url }
      format.json { head :no_content }
    end
  end
  
  def deleteall
    
    ChangeLogging.delete_all
    changeLogging = ChangeLogging.new(:logRecord => 'Log cleared', :user_email => current_user.email)
    changeLogging.save
  end
  
end

app/views/change_loggings/_form.html.erb
<%= form_for(@change_logging) do |f| %>
  <% if @change_logging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@change_logging.errors.count, "error") %> prohibited this change_logging from being saved:</h2>

      <ul>
      <% @change_logging.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dateTime %><br />
    <%= f.datetime_select :dateTimeLogged %>
  </div>
  <div class="field">
    <%= f.label :logRecord %><br />
    <%= f.text_field :logRecord %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/change_loggings/deleteall.html.erb
<h2>Deleted</h2>

app/views/change_loggings/edit.html.erb
<h1>Editing change_logging</h1>

<%= render 'form' %>

<%= link_to 'Show', @change_logging %> |
<%= link_to 'Back', change_loggings_path %>

app/views/change_loggings/index.html.erb
<h2>Change Log</h2>

<%= link_to 'Clear Log', {:controller => :change_loggings, :action => :deleteall}, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small" %>
<hr>
<table class="table table-bordered table-striped table-condensed table-hover">
<thead>
  <tr>
    <th>Log Date/Time</th>
    <th>Record</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @change_loggings.each do |change_logging| %>
  <tr>
    <td><%= change_logging.created_at %></td>
    <td><%= change_logging.logRecord %></td>
    <td><%= link_to 'Destroy', change_logging, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small"  %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Change logging', new_change_logging_path, :class =>"btn btn-primary" %>

app/views/change_loggings/new.html.erb
<h1>New change_logging</h1>

<%= render 'form' %>

<%= link_to 'Back', change_loggings_path %>

app/views/change_loggings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Datetime:</b>
  <%= @change_logging.dateTimeLogged %>
</p>

<p>
  <b>Logrecord:</b>
  <%= @change_logging.logRecord %>
</p>


<%= link_to 'Edit', edit_change_logging_path(@change_logging) %> |
<%= link_to 'Back', change_loggings_path %>