config/routes.rb
SixSigmaWebServce::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  resources :quality_specifications 
  get 'quality_specifications_init' => 'quality_specifications#initialise_db'
  resources :change_loggings
  get 'change_loggings_deleteall' => 'change_loggings#deleteall'
  resources :test_codes
end

app/models/test_code.rb
class TestCode < ActiveRecord::Base
  has_many :quality_specifications
  attr_accessible  :testcodetext,	:testexpansion,	:notes, :active, :readcode

require 'csv'

def self.open_spreadsheet(file)
  	case File.extname(file.original_filename)
  		when ".csv" then Csv.new(file.path, nil, :ignore)
  		when ".xls" then Excel.new(file.path, nil, :ignore)
  		when ".xlsx" then Excelx.new(file.path, nil, :ignore)
  	else raise "Unknown file type: #{file.original_filename}"
  	end
end
  
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |specificaiton|
      csv << specificaiton.attributes.values_at(*column_names)
    end
  end
end

def self.import(file)  
  CSV.foreach(file.path, headers: true) do |row|  
    TestCode.create! row.to_hash  
  end 
end
  
  
end

app/controllers/test_codes_controller.rb
class TestCodesController < ApplicationController
  
  # before_filter :authenticate_user!
  
  # GET /test_codes
  # GET /test_codes.json
  def index
    @test_codes = TestCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json 
      format.csv { send_data TestCode.to_csv }
      format.xls # { send_data @TestCode.to_csv(col_sep: "\t")}
    end
  end
  

  # GET /test_codes/1
  # GET /test_codes/1.json
  def show
    @test_code = TestCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_code }
    end
  end

  # GET /test_codes/new
  # GET /test_codes/new.json
  def new
    @test_code = TestCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_code }
    end
  end

  def generate
    @gentest = TestCode.generate_test_codes_from_ams_data
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_code }
    end
    
  end


  # GET /test_codes/1/edit
  def edit
    @test_code = TestCode.find(params[:id])
  end

  # POST /test_codes
  # POST /test_codes.json
  def create
    @test_code = TestCode.new(params[:test_code])

    respond_to do |format|
      if @test_code.save
        
        @test_code.users_id = current_user.id
        changeLogging = ChangeLogging.new(:logRecord => 'Test Code Created', :users_id => current_user.id)
        changeLogging.save
        
        format.html { redirect_to @test_code, notice: 'Test code was successfully created.' }
        format.json { render json: @test_code, status: :created, location: @test_code }
      else
        format.html { render action: "new" }
        format.json { render json: @test_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_codes/1
  # PUT /test_codes/1.json
  def update
    @test_code = TestCode.find(params[:id])

    respond_to do |format|
      if @test_code.update_attributes(params[:test_code])
        changeLogging = ChangeLogging.new(:logRecord => 'Test code updated: '+ params[:test_code].to_s, :users_id => current_user.id)
        changeLogging.save
        format.html { redirect_to @test_code, notice: 'Test code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_codes/1
  # DELETE /test_codes/1.json
  def destroy
    @test_code = TestCode.find(params[:id])
    @test_code.destroy

    respond_to do |format|
      format.html { redirect_to test_codes_url }
      format.json { head :no_content }
    end
  end
end

app/views/test_codes/_form.html.erb
<%= form_for @test_code, :html => {:class => "form-horizontal well"}  do |f| %>
  <% if @test_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_code.errors.count, "error") %> prohibited this test_code from being saved:</h2>

      <ul>
      <% @test_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<legend>Add/Edit Test Code Details</legend>
<fieldset>
	<div class="control-group">
		<%= label_tag(:testcodetext, "Telepath Testcode", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :testcodetext%>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:testexpansion, "Test Expansion", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :testexpansion%>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:notes, "Notes", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :notes%>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:active, "Active", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :active%>
		</div>
	</div>

		<div class="form-actions">
			<%= f.submit :class => "btn-primary" %>
		</div>
	<fieldset>
	<% end %>

app/views/test_codes/add_ams_test_codes.html.erb
<% if @iqc == false %>
	<div id="error_explanation">
		<div class="alert alert-error">
		Error Adding Record
		</div>
	</div>
<% else %>
<div class="alert alert-success">
Record Imported
</div>
<% end %>

app/views/test_codes/ams_test_codes.html.erb
<div class="row">
  <div class="span6">
	<span class="label label-success">Test Codes In System</span></br>
	<ul>
  	<% @iqc.each do |iqc| %>
		<li><%=iqc.testCodeText%></li>
	<%end%>
	</ul>
  </div>

<div class="span6">
	<span class="label label-success">Test Codes in AMS</span></br>
	<ul>
  	<% @ams.each do |ams| %>
		<li><%=ams.testname%></li>
	<%end%>
	</ul>
  </div>
</div>
<div class="row">
	<% if @diffs.empty? %>
	<div class="alert alert-success">
		No differences found
		</div>
		<%else%>
		Differences: <%=@diffs%>
		<%= link_to "Add unimported Test",  test_codes_add_ams_test_codes_path(:testname => @diffs[0].testname) %>
		<%end%>	
</div>

app/views/test_codes/create.html.erb
<h1>TestCodes#create</h1>
<p>Find me in app/views/test_codes/create.html.erb</p>

app/views/test_codes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @test_code, :class=>"btn btn-success" %> |
<%= link_to 'Back', test_codes_path, :class=>"btn btn-inverse" %>

app/views/test_codes/generate.html.erb
Auto Generated the following testcodes:<br>
<table class="table table-bordered table-striped table-condensed table-hover">
  <tr>
    <th>Testname</th>
  </tr>

<% @gentest.each do |qc| %>
  <tr>
	<td><%= qc.testname %> </td>
  </tr>
<% end %>
</table>

app/views/test_codes/index.html.erb
<h2>Listing currently configured Tests</h2>

<table class="table table-bordered table-striped table-condensed table-hover">
<thead>
  <tr>
    <th>Telepath Test Code</th>
    <th>Notes</th>
    <th>Active</th>
    <th>Test Expansion</th>
    <th>Internal Test Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tfoot>
    	<tr>
        	<td colspan="7"><em>Test code management functions</em></td> 
        </tr>
    </tfoot>
<% @test_codes.each do |test_code| %>
  <tr>
	<td><%=test_code.testcodetext %> </td>
	<td><%=test_code.notes %> </td>
	<td><% if test_code.active == TRUE %>
	Active
  <% else %>
	Inactive
  <% end%></td>
	<td><%=test_code.testexpansion %> </td>
	<td><%=test_code.id %> </td>
    <td><%= link_to 'Show', test_code, :class => "btn btn-info btn-small"   %></td>
    <td><%= link_to 'Edit', edit_test_code_path(test_code), :class => "btn btn-primary btn-small"   %></td>
    <td><%= link_to 'Destroy', test_code, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small"   %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Test', new_test_code_path, :class =>"btn btn-primary" %>
<hr>



<p>
  Download:
  <%= link_to "CSV", test_codes_path(format: "csv") %> |
  <%= link_to "Excel", test_codes_path(format: "xls") %>
</p>
<br />

app/views/test_codes/new.html.erb
<h2>New test code</h2>

<%= render 'form' %>

<%= link_to 'Back', test_codes_path, :class=>"btn btn-inverse" %>

app/views/test_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p id="notice"><%= notice %></p>

<p>
  <b>Test Code (Read Code):</b>
  <%= @test_code.readcode %>
</p>

<p>
  <b>Test Code (Telepath):</b>
  <%= @test_code.testcodetext %>
</p>

<p>
  <b>Full name:</b>
  <%= @test_code.testexpansion %>
</p>

<p>
  <b>Notes:</b>
  <%= @test_code.notes %>
</p>

<p>
  <b>Active:</b>
  <% if @test_code.active == TRUE %>
	Active
  <% else %>
	Inactive
  <% end%>
</p>

<%= link_to 'Edit', edit_test_code_path(@test_code), :class=>"btn btn-success" %> |
<%= link_to 'Back', test_codes_path, :class=>"btn btn-inverse" %>